### ISSUE TITLE
Classes with S1 or S2 in the name do not appropriately add to the quickbar when the main class is present.

### ISSUE THREAD

**Issue by jtd8414** [MatthewGalan/mycourses-plus#11]
I attempted to add MLAS.201.04S2 to the quick bar when I already had MLAS.201.04 on the quickbar. I expected  MLAS.201.04S2 be added alongside MLAS.201.04 but instead the page was reloaded and the add button remained.

![image](https://user-images.githubusercontent.com/32747127/98341536-fba39500-1fdc-11eb-8d86-fe06e3523d3c.png)

**Comment by MattGalan** [comment]
This is because courses are currently only identified by their short code, such as `SWEN.440`. This will require some tweaks to the script but shouldn't be a huge issue. The code is in [`quickbar.js`](https://github.com/MatthewGalan/mycourses-plus/blob/master/quickbar.js).

**Comment by MattGalan** [comment]
Thanks for the bug report! I've reworked `quickbar.js` in 415b67570666ae070610bcd17af2b976c2465d6f. The full course code will be displayed in cases where two or more courses with the same short code are found. See below for an example.

Before adding:
![image](https://user-images.githubusercontent.com/20482179/98739572-99011f00-2377-11eb-89bd-b009a0835d62.png)

After adding:
![image](https://user-images.githubusercontent.com/20482179/98739595-9f8f9680-2377-11eb-9132-d9ea98f34b3b.png)
