### ISSUE TITLE
Hide navigation menu visual indicators

### ISSUE THREAD

**Issue by jtd8414** [MatthewGalan/mycourses-plus#14]
On all class pages there is a Hide dropdown menu that allows users to hide specific navigation tabs from the menu. It would be nice if the hide menu displayed a visual indicator for each tab in the hide dropdown that showed which tabs are currently hidden and which ones are visible. See `hide_useless\hideNav.js` for the code that injects the hide dropdown menu.  

![image](https://user-images.githubusercontent.com/32747127/98409042-2d017c80-2040-11eb-8990-888e9db10cb5.png)

**Comment by MattGalan** [comment]
I've took a stab at it in 404641213c164d5e2dfb88cdfb4f1da5c603c830. It's a little rough but it does the job and is already proving useful.

![image](https://user-images.githubusercontent.com/20482179/100189103-9c3cf480-2eb9-11eb-9d8a-e9c2f3369be7.png)


I'll close the issue for now, but feel free to enhance as you see fit.
