### ISSUE TITLE
Regex bug: course has valid longCode but undefined shortCode

### ISSUE THREAD

**Issue by MJVL** [MatthewGalan/mycourses-plus#17]
## Issue
When messing around I noticed this in my quickBar.

![image](https://user-images.githubusercontent.com/29935794/98884538-43ec0880-245e-11eb-8e03-db20aecbe435.png)

Despite this class being seemingly valid, adding it to the quickBar spits out loads of undefineds.

## Possible Reasoning
Taking a quick look at the code and logging both shortCode and longCode reveal that the longCode is parsed correctly, while the shortCode's regex has no matches, ending in undefined.

```
shortCode: undefined
longCode: CRIM/WGST.245.01 
```
## Repro Information
Course Code: `CRIM/WGST.245.01`
Long Name: `CRIM/WGST.245.01 - Prostitution and Vice (CRIM24501.2201)`

**Comment by MattGalan** [comment]
This is hopefully fixed in db8345882609d0decfa48ee66fb4ad762d6e7a47. Would you mind pulling the latest, refreshing the extension, and checking to see if it worked? Thanks!

**Comment by MJVL** [comment]
Yup, seemingly all good now!
