### ISSUE TITLE
Assignments sometimes don't sort by score properly

### ISSUE THREAD

**Issue by Bradley-B** [MatthewGalan/mycourses-plus#6]
Sometimes, assignment scores have a percentage, like this: 
![image](https://user-images.githubusercontent.com/12214204/98146489-96935680-1e99-11eb-98b7-ebad83383806.png)

Instead of like this: 
![image](https://user-images.githubusercontent.com/12214204/98146740-c93d4f00-1e99-11eb-9349-4c4b38842e7c.png)

This messes up sorting by score. Planning a PR to fix this.

**Comment by MattGalan** [comment]
Excellent catch! None of my professors do the percentage thing, which is probably why I missed that.

I'll approve the PR now!

**Comment by Bradley-B** [comment]
Yeah, I didn't notice it yesterday when I was working on the assignment table because I wasn't testing it with a class that did that. Seems like there are a lot of little things that change based on how the professor has a class configured, so we just need to keep an eye out.
