### ISSUE TITLE
Hide useless panels on course page

### ISSUE THREAD

**Issue by MattGalan** [MatthewGalan/mycourses-plus#9]
There's several useless panels present on each course page, such as "Academic Integrity," "ADA Statement," and "myCourses Communication Policy." There's also several links in the nav toolbar that no one uses, including "Starfish," "My Library," and "Help."

To remove these elements, I would create a new file in the `hide_useless/` folder called `coursepage.js` or something similar. `hide_useless/homepage.js` should work well as an example. Then, modify `manifest.json` so your script is injected when viewing a course page.

**Comment by jtd8414** [comment]
@MatthewGalan I have changes for hiding nav items within the nav toolbar. I don't seem to have permission to create a branch to create a pull request. So if you give me permissions or let me know how else I can create a pull request I would be happy to contribute to this project :)

**Comment by MattGalan** [comment]
@jtd8414 Awesome, thank you! I've given you access to the repo so you should be free to create a branch and then make a PR to `master` when you're ready. You can also fork the repo if you prefer.

@Bradley-B I know you've got a fork, but if you'd like access as well just let me know.
